### ISSUE TITLE
Content deduplication

### ISSUE THREAD

**Issue by Diomas** [textileio/textile-go#136]
Hi,

Does textile support decoupling file content from its meta data? If it supposed to have social "share" function and let's say people start using it for sharing memes from different sources, more likely it going to be same image data with different EXIF (or some other headers).

Another example: some friend of mine shared a photo with me and I want to share it to some group but I would definitely want to skip location and maybe some other meta from it. There should be more optimal way than just to keep two copies of the same image data on the disk. Moreover imagine, we talk about 2Gb video file.

[These guys](https://github.com/perkeep/perkeep/) are working on something similar (storage over ipfs) and they address this issue by dividing all the data into some blobs (which are not one-to-one files, but some more low-level chunks)
https://youtu.be/PlAU_da_U4s?t=671 here they are talking something about the storage and content deduplication

**Comment by Diomas** [comment]
https://youtu.be/PlAU_da_U4s?t=1121 here are more details

**Comment by sanderpick** [comment]
Hi @Diomas, thanks for the info and links! Definitely will check it out.

We've just made a large around file / photo encryption (#127). Our first naive / brute force sharing impl. would just decrypt the photo, thumb, and meta data (a DAG structure on IPFS), re-encrypt with the new "thread" public key, and add the resultant files to IPFS. Certainly not ideal, but was meant to be POC. The new approach encrypts each file in the DAG with a one-off AES key, which is then encrypted with the "thread" public key and added to a different object / structure we're calling a `Block`. `Thread`s are composed of these `Blocks`, which form a git-like chain. If you have the thread's private key, you can decrypt the files referred to by the blocks. A thread can contain content from just you, two people, a group, etc. I'm refraining from calling a `Thread` a blockchain because it currently doesn't have any consensus mechanism (and may never).

Here's an example of a photo directory / DAG:
https://ipfs.textile.io/ipfs/QmNd9aAmUoN9APaLUSqbsJ8gPjNMTUBfUk5UB2aEWUCjmj

And it's `Block`:
https://ipfs.textile.io/ipfs/Qmdu2AqJdGrtaxykdqE5wyaRav6YBr6uycKNwBgXECmgAe

This solves the problem of a single file / photo being duplicated. You can see the `caption` on a photo is part of the `Block` and not the file itself.

Related to your mention of EXIF data, I have an open PR which just strips all EXIF data for now (#138). You got me thinking that what we ought to do here is encrypt the meta data with it's own AES key so it can be shared / not-shared alongside the file / image. The meta data could also be saved in more smaller files, so you could choose exactly what to share. Currently, we're just writing it all as JSON to a file: https://github.com/textileio/textile-go/blob/master/wallet/model/model.go#L28

We don't yet support video... but it's on the roadmap. I've heard rumors of IPFS planning on natively handling encryption at the chunk / block level, which would be great for streaming. Still, your concerns around meta data would apply.

What do you think? Sound reasonable?
