### ISSUE TITLE
trouble building desktop client

### ISSUE THREAD

**Issue by whyrusleeping** [textileio/textile-go#219]
After a few dependency issues (the makefile doesnt fetch dependencies, needed a `go get` and `gx install`) I ran into this:
```
FATA[0082] bundling failed: bundling for environment darwin/amd64 failed: building failed: # github.com/textileio/textile-go/desktop
./bootstrap.go:24:11: unknown field 'Homepage' in struct literal of type bootstrap.Options
./bootstrap.go:25:17: unknown field 'MessageHandler' in struct literal of type bootstrap.Options
./bootstrap.go:26:9: cannot use start (type func(*astilectron.Astilectron, *astilectron.Window, *astilectron.Menu, *astilectron.Tray, *astilectron.Menu) error) as type bootstrap.OnWait in field value
./bootstrap.go:28:16: unknown field 'WindowOptions' in struct literal of type bootstrap.Options
: exit status 2  app_name=
make[1]: *** [build] Error 1
make: *** [build_desktop] Error 2
```

**Comment by sanderpick** [comment]
Ohhh, yep, that's confusing... I recently reorganized the readme and moved the setup stuff to the bottom, below the desktop instructions :) I _think_ that looks like a version mismatch. We're using a combo of `dep` and `gx`, so I bundled the install into a single `npm run setup`. Three dependencies managers! So, if you do that (or just run `dep ensure` since you've got the gx deps) you should get the correct go-astilectron version, as specified in the `Gopkg.lock`.

Thanks for all the alpha testing :)

**Comment by whyrusleeping** [comment]
Sweet, progress! Now it builds, but when running it i get this:
<img width="424" alt="screen shot 2018-08-02 at 9 41 15 am" src="https://user-images.githubusercontent.com/1243164/43597891-3bc17c6e-9638-11e8-98e9-c39a7ed5cd12.png">

**Comment by carsonfarmer** [comment]
Hmm, we've had this issue before. I think it relates to this problem:
https://github.com/asticode/go-astilectron/issues/107 which required manually editing the astilectron version. Here's a similar issue: https://github.com/asticode/go-astilectron/issues/51 The fix there is actually better if it works.

**Comment by carsonfarmer** [comment]
@whyrusleeping if you run the desktop app in dev mode with verbose outputs, that might confirm my suspicion above:
```
cd desktop/
go run *.go -v -d
```

**Comment by carsonfarmer** [comment]
Hmm yes I think this is the issue. Bummer. Does `astilectron-bundler -v` mention astilectron version 0.22.0 whereas running mentions 0.20.0? If yes, one 'hacky' fix is to decrease the astilectron version specified in `go-astilectron/astilectron.go`. The more 'correct' fix is (from that other ticket):

* when you execute `astilectron-bundler -v`, the `astilectron` version is the one at the time of building the bundler
* when you execute `go run *.go -v -d`, the `astilectron` version is the current one in the astilectron package
* therefore your astilectron package must be out of date?

Try:

* make sure the `astilectron` package is up to date (and version is v0.22.0)
* (re)install the bundler `go install github.com/asticode/go-astilectron-bundler/astilectron-bundler`
* run your commands again and 🤞

**Comment by sanderpick** [comment]
@whyrusleeping figured it out on Thursday... the issue arises when you `go get` and then `dep ensure` (or `npm run setup`), resulting in multiple versions of `go-astilectron`, one in your go path and one vendor-ed. The fix is to...

1. Blast `$GOPATH/src/github.com/asticode`
2. Reinstall the tools
```
go get -u github.com/asticode/go-astitools
go get -u github.com/asticode/go-astilectron-bundler/...
go get -u github.com/asticode/go-astilectron-bootstrap/...
```
3. Run `dep ensure` just to be sure (he he)
4. `cd desktop && make build`

@asutula would you mind trying this?

**Comment by asutula** [comment]
Following those instructions, I was able to build with no errors. Still getting this when I `open desktop/output/darwin-amd64/Textile.app`:
<img width="532" alt="screen shot 2018-08-07 at 11 05 35" src="https://user-images.githubusercontent.com/528969/43788020-099b4f64-9a32-11e8-8e43-9954c7b35ea6.png">

**Comment by sanderpick** [comment]
@asutula thanks, seems there is still some go path / linking issue on your machine, may also need to use go clean to wipe binaries, but this isn't sustainable...  I think we just need to update to latest go-astilectron. Will shove that into my current work...

**Comment by sanderpick** [comment]
I added an expanded desktop building section to #224: https://github.com/textileio/textile-go/tree/sander/welcome-messages#the-desktop-application

Was finally able to make my local setup generate your failure @asutula. In the end I went with vendoring the actual bundler since it's nice to control the all these related astilectron deps. So after ^ is merged, wipe everything, install the vendored bundler, and finally make:

```
go clean -i github.com/asticode/go-astilectron...
go clean -i github.com/asticode/go-astitools...
go clean -i github.com/asticode/go-astilectron-bundler/...
go clean -i github.com/asticode/go-astilectron-bootstrap/...

rm -rf $GOPATH/src/github.com/asticode
rm -rf vendor

brew upgrade dep # bump to v0.5.0 feels much faster
npm run setup

go install ./vendor/github.com/asticode/go-astilectron-bundler/astilectron-bundler

make build_desktop
```
