### ISSUE TITLE
Post migration method, addPeerToThread(byId)

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#336]
Concept is to allow you to add a peer to an already joined thread by their peerid without the need to send an invite.

**Comment by sanderpick** [comment]
This could cause recovery issues if you never get an actual JOIN from the peer you added.

**Comment by sanderpick** [comment]
@andrewxhill I think we'll have to skip this. Sounds dangerous to skip the invite flow in general, but also technically tough without the ability to add a block on another peer's behalf.

**Comment by andrewxhill** [comment]
okay, gets foggy for me how the peerid swap table will work for bootstrapping threads without it (since everyone would have new peer ids but no peers in their threads to send a new share/head)

**Comment by asutula** [comment]
The peers would exist in the contacts table, right? I guess users would have to re-invite contacts to threads?

**Comment by sanderpick** [comment]
it would work to just add the peer to the thread_peers table like you're saying, but am just worried about recovery. although, thinking more, if everyone re-joins, those blocks should eventually make it to everyone... just gonna be a maximally wide hash tree since every subsequent add will be a merge, but shouldn't really matter

**Comment by sanderpick** [comment]
(the joins are needed to re-pick up the peers during a thread recovery)
