### ISSUE TITLE
Strip location exif from photos in shared Threads

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-go#68]
We could later include optional fields in the off-image metadata model that is shared.

**Comment by andrewxhill** [comment]
this is for shared threads, not for private data

**Comment by andrewxhill** [comment]
so the idea is you would always keep the original intact. but upon sharing you would want to strip and have more control over what parts you shared. so for example, is someone created a thread like, PeopleOfToronto and shared the invite openly, i may not want to allow my location data into such a public thread

**Comment by sanderpick** [comment]
hey @gpestana! will get to your CRDT comment here in a bit, but thanks for chiming in!

**Comment by sanderpick** [comment]
Like you said, this would be easier if we already had an overview doc. I'll do short one here related to this issue.

Alongside the full res photo, we store a thumbnail and a `Metadata` object, which hold the exif data. These all end up as files in a virtual directory dag structure in IPFS. The files are individually encrypted with the album's key. room = album = thread, need to replace everything else with "thread", but using album here because that's still the current usage in code. We call this whole thing a `PhotoSet`. `PhotoSet`s also include a text file that holds the root hash of the previous set. This is where the "blockchain-iness" comes in, although that's a generous description. Lastly, the `Metadata` object is indexed as a row in the `photos` sqlite table, which is used to list, query, etc. what photos are available in what album.

So, to do provide this option to strip the location data, it would have to be removed from the full res photo itself (and the thumb if the data makes it there too), and the `Metadata` object, before being added to the network + the nodes local sqlite db.

This is where the photo and it's thumb are turned into one of these `PhotoSet`s:

https://github.com/textileio/textile-go/blob/master/repo/photos/photos.go#L41

All nodes have a `default` album. In beta, we've created a shared `beta` album to test sharing. This `Add` method above is used for adding and sharing a photo to a thread.

Hopefully that helps shed some light!
